name: driipa_reloaded
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1
  http: ^1.1.0
  scroll_date_picker: ^3.7.3
  shared_preferences: ^2.2.1
  walletconnect_flutter_v2: ^2.1.4
  web3auth_flutter: ^2.0.0
  web3dart: ^2.4.1

dev_dependencies:
  flutter_app_name: ^0.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_app_name:
  name: "Driipa"

flutter_native_splash:
  color: "#320A67"
  image: assets/images/logo.png
  # background_image: "assets/images/backgroundgradient.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
